name: Hi

on:
  push:
    branches: [master]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # tonistiigi/binfmt 이미지를 이용해 qemu 설치
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0

      # docker buildx 설치
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0

        # secrets를 이용해 Docker Hub 로그인
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: heavyrisem
          password: ${{ secrets.GHCR_PAT }}

      # buildx 명령어로 amd64, arm64, arm/v6, arm/v7 아키텍처 이미지 빌드 및
      - name: Docker Build
        run: docker buildx build --platform linux/amd64,linux/arm64 -t heavyrisem/valorant-store-offer:latest --push .
